name: YAML Linting

on:
  push:
  pull_request:
    branches:

jobs:
  lint:
    name: Lint YAML Files
    runs-on: ubuntu-latest

    steps:
      - name: Lint YAML files
        run: |
            find ../.. -type f -name "*.yml" -o -name "*.yaml" | while read filename; do
              yamllint "$filename"
              echo The files $filename
            done

  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
      # ... other steps to deploy the code
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
